version: '3'

name: rancher

services:
  server:
    image: ${IMAGE:?err}
    privileged: true
    networks:
      default:
        aliases:
          - rancher.windows.home
    volumes:
      - data:/var/lib/rancher
      - kubelet:/var/lib/kubelet
      - cni:/var/lib/cni
      - logs:/var/log
      - ./certificates/windows-rancher-bundle.pem:/etc/rancher/ssl/cert.pem
      - ./certificates/windows-rancher-dec-trad-key.pem:/etc/rancher/ssl/key.pem
      - ./certificates/root-ca.pem:/etc/rancher/ssl/cacerts.pem

  proxy:
    image: haproxy:2.7.6
    networks:
      default:
        aliases:
          - proxy.home
    ports:
     - "443:443"
     - "80:80"
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

networks:
  default:
    name: ${DOCKER_NETWORK:?err}
    external: true

volumes:
  data: {}
  kubelet: {}
  cni: {}
  logs: {}
